// Mocks generated by Mockito 5.4.4 from annotations
// in base_ap/test/widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:base_ap/core/constants/enums/database%20keys/collection_keys.dart'
    as _i10;
import 'package:base_ap/core/resources/data_state.dart' as _i6;
import 'package:base_ap/features/auth/model/credentials.dart' as _i9;
import 'package:base_ap/features/auth/service/auth_service.dart' as _i7;
import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:firebase_database/firebase_database.dart' as _i5;
import 'package:firebase_storage/firebase_storage.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAuth_1 extends _i1.SmartFake implements _i3.FirebaseAuth {
  _FakeFirebaseAuth_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseStorage_2 extends _i1.SmartFake
    implements _i4.FirebaseStorage {
  _FakeFirebaseStorage_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseReference_3 extends _i1.SmartFake
    implements _i5.DatabaseReference {
  _FakeDatabaseReference_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_4<T> extends _i1.SmartFake implements _i6.DataState<T> {
  _FakeDataState_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDocumentReference_5<T extends Object?> extends _i1.SmartFake
    implements _i2.DocumentReference<T> {
  _FakeDocumentReference_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCollectionReference_6<T extends Object?> extends _i1.SmartFake
    implements _i2.CollectionReference<T> {
  _FakeCollectionReference_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  _i3.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_1(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.FirebaseAuth);

  @override
  _i4.FirebaseStorage get storage => (super.noSuchMethod(
        Invocation.getter(#storage),
        returnValue: _FakeFirebaseStorage_2(
          this,
          Invocation.getter(#storage),
        ),
      ) as _i4.FirebaseStorage);

  @override
  _i5.DatabaseReference get rtd => (super.noSuchMethod(
        Invocation.getter(#rtd),
        returnValue: _FakeDatabaseReference_3(
          this,
          Invocation.getter(#rtd),
        ),
      ) as _i5.DatabaseReference);

  @override
  _i8.Stream<_i3.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i8.Stream<_i3.User?>.empty(),
      ) as _i8.Stream<_i3.User?>);

  @override
  _i8.Future<_i6.DataState<void>> signUpWithEmail(
          {required _i9.Credentials? credentials}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [],
          {#credentials: credentials},
        ),
        returnValue:
            _i8.Future<_i6.DataState<void>>.value(_FakeDataState_4<void>(
          this,
          Invocation.method(
            #signUpWithEmail,
            [],
            {#credentials: credentials},
          ),
        )),
      ) as _i8.Future<_i6.DataState<void>>);

  @override
  _i8.Future<_i6.DataState<void>> signInWithEmail(
          {required _i9.Credentials? credentials}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {#credentials: credentials},
        ),
        returnValue:
            _i8.Future<_i6.DataState<void>>.value(_FakeDataState_4<void>(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {#credentials: credentials},
          ),
        )),
      ) as _i8.Future<_i6.DataState<void>>);

  @override
  _i8.Future<_i6.DataState<void>> forgotPassword(
          {required _i9.Credentials? credentials}) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [],
          {#credentials: credentials},
        ),
        returnValue:
            _i8.Future<_i6.DataState<void>>.value(_FakeDataState_4<void>(
          this,
          Invocation.method(
            #forgotPassword,
            [],
            {#credentials: credentials},
          ),
        )),
      ) as _i8.Future<_i6.DataState<void>>);

  @override
  _i8.Future<_i6.DataState<void>> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue:
            _i8.Future<_i6.DataState<void>>.value(_FakeDataState_4<void>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i8.Future<_i6.DataState<void>>);

  @override
  _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>
      addDocumentToCollection(
    _i10.CollectionKeys? collection,
    Map<String, dynamic>? data,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #addDocumentToCollection,
              [
                collection,
                data,
              ],
            ),
            returnValue:
                _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                    _FakeDocumentReference_5<Map<String, dynamic>>(
              this,
              Invocation.method(
                #addDocumentToCollection,
                [
                  collection,
                  data,
                ],
              ),
            )),
          ) as _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>);

  @override
  _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>
      addDocumentToSubCollection(
    _i10.CollectionKeys? collection,
    _i10.CollectionKeys? subCollection,
    Map<String, dynamic>? data,
    _i2.DocumentReference<Map<String, dynamic>>? docRef,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #addDocumentToSubCollection,
              [
                collection,
                subCollection,
                data,
                docRef,
              ],
            ),
            returnValue:
                _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                    _FakeDocumentReference_5<Map<String, dynamic>>(
              this,
              Invocation.method(
                #addDocumentToSubCollection,
                [
                  collection,
                  subCollection,
                  data,
                  docRef,
                ],
              ),
            )),
          ) as _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>);

  @override
  _i8.Future<void> updateDocument({
    required _i10.CollectionKeys? collection,
    required String? docId,
    required Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [],
          {
            #collection: collection,
            #docId: docId,
            #data: data,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteDocument({
    required _i10.CollectionKeys? collection,
    required String? docId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [],
          {
            #collection: collection,
            #docId: docId,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i2.DocumentReference<Map<String, dynamic>>> getUserDocRef() =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserDocRef,
          [],
        ),
        returnValue:
            _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>.value(
                _FakeDocumentReference_5<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getUserDocRef,
            [],
          ),
        )),
      ) as _i8.Future<_i2.DocumentReference<Map<String, dynamic>>>);

  @override
  _i2.CollectionReference<Map<String, dynamic>> getCollectionRef(
          _i10.CollectionKeys? collection) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionRef,
          [collection],
        ),
        returnValue: _FakeCollectionReference_6<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getCollectionRef,
            [collection],
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.DocumentReference<Map<String, dynamic>> getDocumentRef({
    required _i10.CollectionKeys? collection,
    required String? docId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentRef,
          [],
          {
            #collection: collection,
            #docId: docId,
          },
        ),
        returnValue: _FakeDocumentReference_5<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getDocumentRef,
            [],
            {
              #collection: collection,
              #docId: docId,
            },
          ),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i2.CollectionReference<Map<String, dynamic>> getSubCollectionRef({
    required _i10.CollectionKeys? collection,
    required String? docId,
    required _i10.CollectionKeys? subCollection,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubCollectionRef,
          [],
          {
            #collection: collection,
            #docId: docId,
            #subCollection: subCollection,
          },
        ),
        returnValue: _FakeCollectionReference_6<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getSubCollectionRef,
            [],
            {
              #collection: collection,
              #docId: docId,
              #subCollection: subCollection,
            },
          ),
        ),
      ) as _i2.CollectionReference<Map<String, dynamic>>);

  @override
  _i2.DocumentReference<Map<String, dynamic>> getSubDocumentRef({
    required _i10.CollectionKeys? collection,
    required String? docId,
    required _i10.CollectionKeys? subCollection,
    required String? subDocId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubDocumentRef,
          [],
          {
            #collection: collection,
            #docId: docId,
            #subCollection: subCollection,
            #subDocId: subDocId,
          },
        ),
        returnValue: _FakeDocumentReference_5<Map<String, dynamic>>(
          this,
          Invocation.method(
            #getSubDocumentRef,
            [],
            {
              #collection: collection,
              #docId: docId,
              #subCollection: subCollection,
              #subDocId: subDocId,
            },
          ),
        ),
      ) as _i2.DocumentReference<Map<String, dynamic>>);

  @override
  _i8.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
